// <auto-generated />
using System;
using HeatRequest.API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeatRequest.API.Migrations
{
    [DbContext(typeof(HeatRequestAppDbContext))]
    [Migration("20211026143940_NewMigration")]
    partial class NewMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HeatRequest.API.Model.Heat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MakinaId")
                        .HasColumnType("int")
                        .HasColumnName("MakinaId");

                    b.Property<decimal>("Sicaklik")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("Sicaklik");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2")
                        .HasColumnName("Tarih");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Heat");
                });
#pragma warning restore 612, 618
        }
    }
}
